[package]
name = "redis-ns"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = { version="1.0.1", features = ["experimental-api"]}
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
